"""Build the supplier-ready Factory Pack for a fresh, default Faro project (the current design).

Usage (from the repo root): backend/.venv/bin/python scripts/build_factory_pack.py
Uses a temporary database: generates CAD from the template defaults, then writes
docs/factory-pack/<name>.zip (send this), plus open-questions.md and consistency.md
(internal: resolve before sending; never send them). Exits non-zero if a consistency
check fails.
"""

import os
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
os.environ["WORKBENCH_DATA_DIR"] = tempfile.mkdtemp(prefix="factory-pack-")
os.environ.setdefault("WORKBENCH_LLM_PROVIDER", "none")
sys.path.insert(0, str(ROOT / "backend"))
os.chdir(ROOT / "backend")

from app.config import settings  # noqa: E402
from app.db import init_db, new_session  # noqa: E402
from app.services import cad  # noqa: E402
from app.services import factory_pack as fp  # noqa: E402
from app.services.projects import create_project  # noqa: E402

init_db(settings.database_url)
session = new_session()
project = create_project(session, "Faro", template="faro")
model = cad.generate(session, project, cad.current_parameters(project))
session.refresh(project)

out_dir = ROOT / "docs" / "factory-pack"
out_dir.mkdir(parents=True, exist_ok=True)
for old in out_dir.glob("*.zip"):
    old.unlink()
name, data = fp.build_factory_pack(project)
(out_dir / name).write_bytes(data)

c = fp.pack_contents(project)
checks = fp.consistency_checks(project, c)
questions = fp.open_questions(project, c)

lines = [f"# Factory Pack consistency: {project.name}, CAD v{model.version}", "",
         "Internal. Generated by scripts/build_factory_pack.py. Do not send.", "",
         "| Check | Result | Detail |", "|---|---|---|"]
lines += [f"| {x['check']} | {'OK' if x['ok'] else 'FIX'} | {x['detail']} |" for x in checks]
(out_dir / "consistency.md").write_text("\n".join(lines) + "\n")

lines = [f"# Open questions before sending the {project.name} RFQ", "",
         "Internal. Suppliers will ask these; each has a proposed answer. Resolve them, then send the zip.", ""]
for i, q in enumerate(questions, start=1):
    lines += [f"{i}. **{q['topic']}: {q['question']}**", f"   - Why: {q['why']}", f"   - Proposed: {q['proposed']}", ""]
(out_dir / "open-questions.md").write_text("\n".join(lines))

failed = [x for x in checks if not x["ok"]]
print(f"Wrote {(out_dir / name).relative_to(ROOT)} ({len(data) / 1e6:.2f} MB), {len(checks) - len(failed)}/{len(checks)} "
      f"checks OK, {len(questions)} open questions")
for x in failed:
    print(f"  FIX: {x['check']}: {x['detail']}")
sys.exit(1 if failed else 0)
