"""add external quotes

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-05 17:30:28.270836
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('revision_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.Column('quote_date', sa.Date(), nullable=False),
    sa.Column('process', sa.String(length=200), nullable=False),
    sa.Column('material', sa.String(length=200), nullable=False),
    sa.Column('finish', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('dfm_notes', sa.Text(), nullable=False),
    sa.Column('attachment_path', sa.String(length=500), nullable=True),
    sa.Column('attachment_filename', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['revision_id'], ['revisions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('external_quotes')
    # ### end Alembic commands ###
